#!/usr/bin/env python3
"""
bot_listener.py
Long-polling Telegram bot that listens for user replies and advances the
active conversation session.

This runs as a persistent process (managed by systemd). When a report is
generated by cron, deliver_report() creates a session in the database
and sends the first question. From there, this listener handles the loop:
user reply -> match to active session -> record answer -> ask next.

Phase 5 (this file): captures replies, advances session.
Phase 6 (next): writes answers back to vault on session completion.
"""

import os
import sys
import logging
from pathlib import Path

# Set up logging early so we capture import errors
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("/home/vault-reporter/bot-listener.log"),
    ],
)
log = logging.getLogger("bot_listener")

# Defer telegram import until env vars are loaded
try:
    from telegram import Update
    from telegram.ext import (
        Application,
        MessageHandler,
        CommandHandler,
        ContextTypes,
        filters,
    )
except ImportError as e:
    log.error(f"python-telegram-bot not installed: {e}")
    log.error("Run: pip3 install python-telegram-bot --break-system-packages")
    sys.exit(1)

from sessions import (
    get_active_session,
    record_answer,
    skip_current_question,
    close_session,
    get_current_question,
)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")

if not BOT_TOKEN or not CHAT_ID:
    log.error("TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID must be set in .env")
    sys.exit(1)

# Cast to int — Telegram sends chat_id as int in updates
AUTHORISED_CHAT_ID = int(CHAT_ID)


# ---------------------------------------------------------------------------
# Authorisation
# ---------------------------------------------------------------------------

def is_authorised(update: Update) -> bool:
    """Only respond to messages from the configured chat_id."""
    if not update.effective_chat:
        return False
    return update.effective_chat.id == AUTHORISED_CHAT_ID


# ---------------------------------------------------------------------------
# Command handlers
# ---------------------------------------------------------------------------

async def cmd_status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """/status - show active session info."""
    if not is_authorised(update):
        return

    session = get_active_session()
    if not session:
        await update.message.reply_text(
            "No active report session.\n"
            "Next scheduled: Sunday 20:00 (weekly), 06:00 (daily), 1st 08:00 (monthly)."
        )
        return

    q = get_current_question(session)
    total = len(session["questions"])
    answered = len(session["answers"])

    msg = (
        f"*Active session*\n"
        f"Report: {session['report_type']} ({session['report_date']})\n"
        f"Progress: {answered}/{total} answered\n"
        f"Status: {session['status']}\n"
    )
    if q:
        msg += f"\n*Awaiting reply to Q{session['current_q_idx'] + 1}:*\n{q.get('text', '')}"

    await update.message.reply_text(msg, parse_mode="Markdown")


async def cmd_cancel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """/cancel - abandon the active session without writing anything."""
    if not is_authorised(update):
        return

    session = get_active_session()
    if not session:
        await update.message.reply_text("No active session to cancel.")
        return

    close_session(session["id"], final_status="cancelled")
    await update.message.reply_text(
        f"Cancelled session #{session['id']}. "
        f"No answers written. Reports continue to run on schedule."
    )


async def cmd_help(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """/help - show available commands."""
    if not is_authorised(update):
        return

    msg = (
        "*Vault Reporter bot*\n\n"
        "Reports arrive on schedule. When questions are asked, reply with your answer.\n\n"
        "*Commands:*\n"
        "/status - show current session\n"
        "/cancel - abandon the active session\n"
        "/help - this message\n\n"
        "*In a session, reply with:*\n"
        "_(your answer)_ - record and move to next question\n"
        "*skip* - skip current question\n"
        "*done* - end session early, keeping answered questions"
    )
    await update.message.reply_text(msg, parse_mode="Markdown")


# ---------------------------------------------------------------------------
# Message handler — the heart of Phase 5
# ---------------------------------------------------------------------------

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Route any plain message to the active session."""
    if not is_authorised(update):
        log.warning(
            f"Ignored message from unauthorised chat_id "
            f"{update.effective_chat.id if update.effective_chat else 'unknown'}"
        )
        return

    text = update.message.text.strip() if update.message and update.message.text else ""
    if not text:
        return

    session = get_active_session()
    if not session:
        await update.message.reply_text(
            "No active question to answer.\n"
            "Send /status to check, or wait for the next scheduled report."
        )
        return

    # Handle special commands within the conversation
    text_lower = text.lower()

    if text_lower == "done":
        # End the session early — keep answered questions
        close_session(session["id"], final_status="ended_early")
        answered = len(session["answers"])
        total = len(session["questions"])
        await update.message.reply_text(
            f"Session ended early. {answered}/{total} questions answered.\n"
            f"_(Phase 6 will write these to the vault — currently they sit in the session DB.)_",
            parse_mode="Markdown",
        )
        return

    if text_lower == "skip":
        updated = skip_current_question(session["id"])
        await _ask_next_or_finish(update, updated)
        return

    # Normal answer — record it
    updated = record_answer(session["id"], text)
    log.info(
        f"Recorded answer for session {session['id']} "
        f"Q{session['current_q_idx'] + 1}: {text[:60]}"
    )
    await _ask_next_or_finish(update, updated)


async def _ask_next_or_finish(update: Update, session: dict):
    """After recording an answer, ask the next question or close out."""
    total = len(session["questions"])

    if session["status"] == "complete":
        # All questions answered
        await update.message.reply_text(
            f"All {total} questions answered for the {session['report_type']} report.\n\n"
            f"_(Phase 6 will write these to the vault. Currently they're stored in the session DB.)_",
            parse_mode="Markdown",
        )
        return

    # Ask the next question
    next_q = get_current_question(session)
    if not next_q:
        # Shouldn't happen if status logic is right, but be defensive
        await update.message.reply_text(
            "Session complete. (No more questions queued.)"
        )
        return

    q_idx = session["current_q_idx"] + 1  # 1-based for display
    q_text = f"*Q{q_idx}/{total}:* {next_q['text']}"
    if next_q.get("hint"):
        q_text += f"\n\n_{next_q['hint']}_"
    q_text += f"\n\n_Reply with your answer. Send 'skip' to skip, 'done' to end early._"

    await update.message.reply_text(q_text, parse_mode="Markdown")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    log.info("Starting bot listener (long-polling mode)")
    log.info(f"Authorised chat_id: {AUTHORISED_CHAT_ID}")

    app = Application.builder().token(BOT_TOKEN).build()

    # Command handlers
    app.add_handler(CommandHandler("status", cmd_status))
    app.add_handler(CommandHandler("cancel", cmd_cancel))
    app.add_handler(CommandHandler("help", cmd_help))
    app.add_handler(CommandHandler("start", cmd_help))

    # Generic message handler (text, not commands)
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    # Run forever — python-telegram-bot handles long-polling internally
    app.run_polling(
        drop_pending_updates=False,  # We want to handle queued messages too
        allowed_updates=["message"],  # Only care about messages, not edits/etc
    )


if __name__ == "__main__":
    main()
