#!/usr/bin/env python3
"""
bot_listener.py

Long-polling Telegram bot that listens for user replies and advances the
active conversation session.

This runs as a persistent process (managed by systemd). When a report is
generated by cron, deliver_report() creates a session in the database
and sends the first question. From there, this listener handles the loop:
user reply -> match to active session -> record answer -> ask next.

Phase 6+ change: all the conversational scaffolding text (completion lines,
early-end, cancel, status-idle) is now AI-generated at report-generation
time and stored in the session's `messages` blob. This file pulls strings
from there with placeholder substitution, falling back to a small set of
hardcoded defaults only when the AI-generated text is missing.

A "conversational mode" placeholder route is added: when a message arrives
with no active session, the bot replies with a friendly note that a real
conversational assistant isn't built yet. This claims the architectural
slot for the future ad-hoc vault-assistant work.
"""

import os
import sys
import json
import random
import logging
from pathlib import Path

# Set up logging early so we capture import errors
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("/home/vault-reporter/bot-listener.log"),
    ],
)
log = logging.getLogger("bot_listener")

# Defer telegram import until env vars are loaded
try:
    from telegram import Update
    from telegram.ext import (
        Application,
        MessageHandler,
        CommandHandler,
        ContextTypes,
        filters,
    )
except ImportError as e:
    log.error(f"python-telegram-bot not installed: {e}")
    log.error("Run: pip3 install python-telegram-bot --break-system-packages")
    sys.exit(1)

from sessions import (
    get_active_session,
    record_answer,
    skip_current_question,
    close_session,
    get_current_question,
    get_session,
    db,
)
from vault_writeback import write_session_to_vault
from telegram_sender import render_question

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")

if not BOT_TOKEN or not CHAT_ID:
    log.error("TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID must be set in .env")
    sys.exit(1)

AUTHORISED_CHAT_ID = int(CHAT_ID)

# ---------------------------------------------------------------------------
# Fallback messages — used only when a session has no `messages` blob
# (e.g. sessions created on an older schema). Match the defaults in
# report_generator.py so behaviour is consistent.
# ---------------------------------------------------------------------------

FALLBACK_MESSAGES = {
    "completion_clean": "Got it — {written} written back to the vault.",
    "completion_partial": "Got it. {written} of {total} written, {failed} didn't take. I've left a log entry.",
    "completion_total_fail": "That didn't land — none of the {total} made it to the vault. Log entry's there.",
    "early_end": "Saving what we've got — {written} of {total} written, the rest dropped.",
    "early_end_zero": "Dropped, nothing written.",
    "cancel": "Cancelled. Nothing written. Reports continue on schedule.",
    "status_idle": "Nothing live right now. Next up: daily 06:00, weekly Sunday 20:00, monthly 1st 08:00.",
}

def _msg(session: dict | None, key: str, **kwargs) -> str:
    """
    Pull a conversational message from the session's messages blob.
    Substitute {written}, {total}, {failed} placeholders. Fall back to
    FALLBACK_MESSAGES if the AI-generated text isn't available.
    """
    template = None
    if session and session.get("messages"):
        template = session["messages"].get(key)
    if not template:
        template = FALLBACK_MESSAGES.get(key, "")
    if not template:
        return ""
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError, ValueError) as e:
        log.warning(f"[bot] placeholder substitution failed for {key}: {e}; using raw template")
        return template

# ---------------------------------------------------------------------------
# Authorisation
# ---------------------------------------------------------------------------

def is_authorised(update: Update) -> bool:
    """Only respond to messages from the configured chat_id."""
    if not update.effective_chat:
        return False
    return update.effective_chat.id == AUTHORISED_CHAT_ID

# ---------------------------------------------------------------------------
# Command handlers
# ---------------------------------------------------------------------------

async def cmd_status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """/status - show active session info."""
    if not is_authorised(update):
        return

    session = get_active_session()
    if not session:
        # No active session — pull the friendly status-idle line from any
        # recent completed session, or fall back to the default.
        with db() as conn:
            row = conn.execute(
                "SELECT messages_json FROM sessions ORDER BY id DESC LIMIT 1"
            ).fetchone()
        if row:
            try:
                msgs = json.loads(row["messages_json"]) if row["messages_json"] else {}
            except Exception:
                msgs = {}
        else:
            msgs = {}
        text = msgs.get("status_idle") or FALLBACK_MESSAGES["status_idle"]
        await update.message.reply_text(text)
        return

    # Active session — show progress factually.
    q = get_current_question(session)
    total = len(session["questions"])
    answered = len(session["answers"])
    rt = session["report_type"]

    msg = (
        f"*Live: {rt} report*\n"
        f"{answered}/{total} answered, status: {session['status']}\n"
    )
    if q:
        framing = q.get("framing") or q.get("text") or "(question text missing)"
        msg += f"\n*Waiting on:*\n{framing}"
    await update.message.reply_text(msg, parse_mode="Markdown")

async def cmd_cancel(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """/cancel - abandon the active session without writing anything."""
    if not is_authorised(update):
        return

    session = get_active_session()
    if not session:
        await update.message.reply_text("Nothing to cancel.")
        return

    close_session(session["id"], final_status="cancelled")
    await update.message.reply_text(_msg(session, "cancel"))

async def cmd_help(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """/help - show available commands."""
    if not is_authorised(update):
        return
    # Keep this plain and short — it's reference, not voice
    msg = (
        "Vault Reporter\n\n"
        "Reports arrive on schedule. When questions come, reply to answer.\n\n"
        "Commands:\n"
        "/status — what's live right now\n"
        "/cancel — drop the current session\n"
        "/help — this message\n\n"
        "In a session: send your answer, or `skip` / `done`."
    )
    await update.message.reply_text(msg)

# ---------------------------------------------------------------------------
# Message handler — routes replies into the active session
# ---------------------------------------------------------------------------

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Route any plain message to the active session, or to the conversational placeholder."""
    if not is_authorised(update):
        log.warning(
            f"Ignored message from unauthorised chat_id "
            f"{update.effective_chat.id if update.effective_chat else 'unknown'}"
        )
        return

    text = update.message.text.strip() if update.message and update.message.text else ""
    if not text:
        return

    session = get_active_session()
    if not session:
        # No active session — route to the conversational placeholder.
        # Future: this is where the ad-hoc vault assistant lives.
        await _handle_conversational(update, text)
        return

    # Handle special in-session commands
    text_lower = text.lower()
    if text_lower == "done":
        await _handle_done(update, session)
        return
    if text_lower == "skip":
        updated = skip_current_question(session["id"])
        await _ask_next_or_finish(update, updated)
        return

    # Normal answer — record and advance
    updated = record_answer(session["id"], text)
    log.info(
        f"Recorded answer for session {session['id']} "
        f"Q{session['current_q_idx'] + 1}: {text[:60]}"
    )
    await _ask_next_or_finish(update, updated)

# ---------------------------------------------------------------------------
# Conversational placeholder route
# ---------------------------------------------------------------------------

# A small bank of replies for "user texted with no session active". These are
# the only hardcoded chat replies left in the codebase — they're a placeholder
# until the real conversational assistant ships. Plain, mildly varied to avoid
# the exact same line every time, and uses the same anti-pattern rules as
# voice (no service-y phrasing, no exclamation marks).
PLACEHOLDER_REPLIES = [
    "Not built for free-form chat yet — that's coming. For now I only speak when a report has questions. /status to see what's live.",
    "Conversational mode isn't live yet. I only handle replies to scheduled reports. /status if you're not sure what's running.",
    "No question on the table right now, and I can't do open conversation yet. Soon. /status to check.",
]

async def _handle_conversational(update: Update, text: str):
    """
    Route for messages that arrive with no active session.

    Today this just sends a placeholder. The slot exists so when the real
    vault-assistant work happens later, this is the function that gets
    rewritten — bot architecture stays the same.
    """
    reply = random.choice(PLACEHOLDER_REPLIES)
    log.info(f"[conversational] placeholder reply to: {text[:60]}")
    await update.message.reply_text(reply)

# ---------------------------------------------------------------------------
# Session flow helpers
# ---------------------------------------------------------------------------

async def _handle_done(update: Update, session: dict):
    """User typed 'done' mid-session. Save what we have, write to vault."""
    close_session(session["id"], final_status="ended_early")
    answered = len(session["answers"])
    total = len(session["questions"])

    # Re-fetch with the up-to-date status
    final_session = get_session(session["id"])

    if answered == 0:
        # Nothing to write
        await update.message.reply_text(_msg(session, "early_end_zero"))
        return

    # Write what we've got
    summary = write_session_to_vault(final_session)

    # Build the response from the AI-generated early_end template
    msg = _msg(
        session,
        "early_end",
        written=summary.get("written", 0),
        total=total,
        failed=summary.get("failed", 0),
    )
    await update.message.reply_text(msg)

async def _ask_next_or_finish(update: Update, session: dict):
    """After recording an answer, ask the next question or close out."""
    total = len(session["questions"])

    if session["status"] == "complete":
        # All questions answered — write to vault
        summary = write_session_to_vault(session)
        written = summary.get("written", 0)
        failed = summary.get("failed", 0)

        # Pick the right completion template based on actual results
        if failed == 0 and written > 0:
            key = "completion_clean"
        elif written == 0 and failed > 0:
            key = "completion_total_fail"
        else:
            key = "completion_partial"

        msg = _msg(
            session,
            key,
            written=written,
            total=total,
            failed=failed,
        )
        await update.message.reply_text(msg)
        return

    # Ask the next question
    next_q = get_current_question(session)
    if not next_q:
        # Defensive: shouldn't happen if status logic is right
        log.warning(f"[bot] session {session['id']} in_progress but no current question")
        return

    await update.message.reply_text(render_question(next_q), parse_mode="Markdown")

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    log.info("Starting bot listener (long-polling mode)")
    log.info(f"Authorised chat_id: {AUTHORISED_CHAT_ID}")

    app = Application.builder().token(BOT_TOKEN).build()

    # Command handlers
    app.add_handler(CommandHandler("status", cmd_status))
    app.add_handler(CommandHandler("cancel", cmd_cancel))
    app.add_handler(CommandHandler("help", cmd_help))
    app.add_handler(CommandHandler("start", cmd_help))

    # Generic message handler (text, not commands)
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    app.run_polling(
        drop_pending_updates=False,
        allowed_updates=["message"],
    )

if __name__ == "__main__":
    main()
