#!/usr/bin/env python3
"""
vault_writeback.py
Phase 6: when a Telegram session completes, write the captured answers
back into the correct vault locations and push to GitHub.

Each question generated by Claude carries a `vault_write` field with:
  - file: vault-relative path
  - section: section heading (or null)
  - mode: replace_section | prepend_h2 | append_to_section
  - h2_title: required when mode == prepend_h2

This module:
  1. Reads the cloned vault on the VPS
  2. Applies each answer to the right file using the right mode
  3. Stages, commits, and pushes the changes
  4. Mac's Git plugin pulls them automatically into Obsidian

Skipped answers (text == '[SKIPPED]') are ignored — nothing written.
"""

import os
import re
import logging
import subprocess
from pathlib import Path
from datetime import datetime

log = logging.getLogger(__name__)

VAULT_PATH = Path(os.path.expanduser(
    os.environ.get("VAULT_PATH", "/home/vault-reporter/vault")
))


# ---------------------------------------------------------------------------
# Write-mode implementations
# ---------------------------------------------------------------------------

def _split_frontmatter(content: str) -> tuple[str, str]:
    """Split a markdown file into (frontmatter_block, body). Either may be ''."""
    if not content.startswith("---"):
        return "", content
    end = content.find("\n---", 3)
    if end == -1:
        return "", content
    fm = content[: end + 4]
    body = content[end + 4 :].lstrip("\n")
    return fm, body


def _find_section_range(body: str, heading: str) -> tuple[int, int] | None:
    """
    Find the byte range of a `## heading` section in `body`.
    Returns (start, end) where:
      - start = index of the line *after* the heading line
      - end   = index of the next `## ` heading (or end of body)
    Returns None if the heading isn't found.
    """
    # Match `## heading` at start of line, allow trailing whitespace
    pattern = re.compile(r"^## " + re.escape(heading) + r"\s*$", re.MULTILINE)
    match = pattern.search(body)
    if not match:
        return None

    section_start = match.end()
    # Skip the newline immediately after the heading
    if section_start < len(body) and body[section_start] == "\n":
        section_start += 1

    # Find the next ## heading
    next_pattern = re.compile(r"^## ", re.MULTILINE)
    next_match = next_pattern.search(body, section_start)
    section_end = next_match.start() if next_match else len(body)
    return section_start, section_end


def write_replace_section(file_path: Path, heading: str, new_content: str) -> bool:
    """Replace the content of a named section with new_content."""
    if not file_path.exists():
        log.error(f"[writeback] file not found: {file_path}")
        return False

    content = file_path.read_text(encoding="utf-8")
    fm, body = _split_frontmatter(content)

    section_range = _find_section_range(body, heading)
    if section_range is None:
        # Section doesn't exist — append it instead
        log.info(f"[writeback] section '{heading}' not found in {file_path.name}, appending")
        body = body.rstrip() + f"\n\n## {heading}\n\n{new_content.strip()}\n"
    else:
        start, end = section_range
        before = body[:start]
        after = body[end:]
        body = before + new_content.strip() + "\n\n" + after

    file_path.write_text(fm + body if fm else body, encoding="utf-8")
    log.info(f"[writeback] replaced section '{heading}' in {file_path.name}")
    return True


def write_prepend_h2(file_path: Path, h2_title: str, new_content: str) -> bool:
    """Insert a new ## h2_title section at the top of the body (after H1)."""
    if not file_path.exists():
        # If the file doesn't exist, create it with just this entry
        log.info(f"[writeback] file doesn't exist, creating: {file_path}")
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(
            f"# {file_path.stem}\n\n## {h2_title}\n\n{new_content.strip()}\n",
            encoding="utf-8",
        )
        return True

    content = file_path.read_text(encoding="utf-8")
    fm, body = _split_frontmatter(content)

    # Find the first H1 line
    h1_pattern = re.compile(r"^# .+$", re.MULTILINE)
    h1_match = h1_pattern.search(body)

    new_h2_block = f"\n## {h2_title}\n\n{new_content.strip()}\n"

    if h1_match:
        # Insert after the H1 line
        insert_at = h1_match.end()
        # Skip following blank lines
        while insert_at < len(body) and body[insert_at] == "\n":
            insert_at += 1
        body = body[:insert_at] + new_h2_block + "\n" + body[insert_at:]
    else:
        # No H1 — prepend the H2 block at the start
        body = new_h2_block.lstrip("\n") + "\n" + body

    file_path.write_text(fm + body if fm else body, encoding="utf-8")
    log.info(f"[writeback] prepended H2 '{h2_title}' to {file_path.name}")
    return True


def write_append_to_section(file_path: Path, heading: str, new_content: str) -> bool:
    """
    Append content to the end of a named section.
    If heading is empty/None, append to the end of the file instead.
    """
    if not file_path.exists():
        log.error(f"[writeback] file not found: {file_path}")
        return False

    content = file_path.read_text(encoding="utf-8")
    fm, body = _split_frontmatter(content)

    if not heading:
        log.info(f"[writeback] no section specified for {file_path.name}, appending to end of file")
        body = body.rstrip() + "\n\n" + new_content.strip() + "\n"
        file_path.write_text(fm + body if fm else body, encoding="utf-8")
        return True

    section_range = _find_section_range(body, heading)
    if section_range is None:
        # Section doesn't exist — append it as a new section
        log.info(f"[writeback] section '{heading}' not found in {file_path.name}, creating it")
        body = body.rstrip() + f"\n\n## {heading}\n\n{new_content.strip()}\n"
    else:
        start, end = section_range
        # Insert before the end of the section (before next ## or end-of-file)
        existing = body[start:end].rstrip()
        appended = existing + "\n\n" + new_content.strip() + "\n\n"
        body = body[:start] + appended + body[end:]

    file_path.write_text(fm + body if fm else body, encoding="utf-8")
    log.info(f"[writeback] appended to section '{heading}' in {file_path.name}")
    return True


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------

def apply_answer(answer: dict) -> bool:
    """
    Apply a single answer's vault_write instruction.
    Returns True on success, False otherwise.
    """
    text = answer.get("answer", "")
    if not text or text.strip() == "[SKIPPED]":
        log.info("[writeback] skipping empty or skipped answer")
        return True  # Not a failure — just nothing to write

    instr = answer.get("vault_write")
    if not instr or not isinstance(instr, dict):
        log.warning(f"[writeback] no vault_write instructions; skipping answer")
        return False

    file_rel = instr.get("file")
    if not file_rel:
        log.warning("[writeback] vault_write missing 'file'; skipping")
        return False

    file_path = VAULT_PATH / file_rel
    mode = instr.get("mode", "")

    try:
        if mode == "replace_section":
            section = instr.get("section") or ""
            if not section:
                log.warning("[writeback] replace_section missing 'section'")
                return False
            return write_replace_section(file_path, section, text)

        elif mode == "prepend_h2":
            h2_title = instr.get("h2_title") or datetime.now().strftime("%Y-%m-%d") + " — Update"
            return write_prepend_h2(file_path, h2_title, text)

        elif mode == "append_to_section":
            section = instr.get("section") or ""
            # Empty section is now allowed - falls back to appending at EOF
            return write_append_to_section(file_path, section, text)

        else:
            log.warning(f"[writeback] unknown vault_write mode: {mode}")
            return False
    except Exception as e:
        log.error(f"[writeback] exception applying answer: {e}", exc_info=True)
        return False


# ---------------------------------------------------------------------------
# Git operations
# ---------------------------------------------------------------------------

def git_commit_and_push(report_type: str, count: int) -> bool:
    """Stage all changes in the vault and push to GitHub."""
    try:
        # Stage everything
        subprocess.run(["git", "add", "-A"], cwd=VAULT_PATH, check=True)

        # Check if there's anything to commit
        result = subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=VAULT_PATH,
        )
        if result.returncode == 0:
            log.info("[writeback] no vault changes to commit")
            return True

        msg = f"vault: telegram-logged answers ({count}) from {report_type} report"
        subprocess.run(["git", "commit", "-m", msg], cwd=VAULT_PATH, check=True)

        # Push only if a remote exists
        remotes = subprocess.run(
            ["git", "remote"],
            cwd=VAULT_PATH,
            capture_output=True,
            text=True,
        ).stdout.strip()

        if remotes:
            subprocess.run(["git", "push"], cwd=VAULT_PATH, check=True)
            log.info("[writeback] pushed to GitHub")
        else:
            log.info("[writeback] no remote configured — skipping push")

        return True
    except subprocess.CalledProcessError as e:
        log.error(f"[writeback] git command failed: {e}")
        return False


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def write_session_to_vault(session: dict) -> dict:
    """
    Apply all answers from a completed session to the vault.
    Returns a summary dict: {written: N, failed: N, skipped: N}
    """
    answers = session.get("answers", [])
    report_type = session.get("report_type", "report")

    written = 0
    failed = 0
    skipped = 0

    for answer in answers:
        text = answer.get("answer", "")
        if not text or text.strip() == "[SKIPPED]":
            skipped += 1
            continue

        ok = apply_answer(answer)
        if ok:
            written += 1
        else:
            failed += 1

    if written > 0:
        git_commit_and_push(report_type, written)

    summary = {"written": written, "failed": failed, "skipped": skipped}
    log.info(f"[writeback] session complete: {summary}")
    return summary


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    """Standalone — apply the most recently completed session."""
    import sys
    logging.basicConfig(level=logging.INFO)

    from sessions import list_recent

    sessions = list_recent(limit=5)
    completed = [s for s in sessions if s["status"] == "complete"]

    if not completed:
        print("No completed sessions found.")
        sys.exit(0)

    target = completed[0]
    print(f"Applying session #{target['id']} "
          f"({target['report_type']} {target['report_date']}) "
          f"with {len(target['answers'])} answers")
    summary = write_session_to_vault(target)
    print(f"Done: {summary}")
